/**
 * Minimal SoundTouch config for pybind11 build.
 * Normally generated by autoconf, but we create a minimal version.
 */

#ifndef SOUNDTOUCH_CONFIG_H
#define SOUNDTOUCH_CONFIG_H

// Use floating point samples
#define SOUNDTOUCH_FLOAT_SAMPLES 1

// Package info
#define PACKAGE "soundtouch"
#define PACKAGE_VERSION "2.3.2"

// Block size aliases (naming inconsistency fix)
#define INPUT_BLOCK_SIZE 2048
#define DECIMATED_BLOCK_SIZE 256

#endif // SOUNDTOUCH_CONFIG_H
